# Generated by Django 2.1.1 on 2018-09-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='request_limits',
            field=models.IntegerField(default=None),
        ),
    ]
