# Generated by Django 2.1.1 on 2018-09-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_is_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='request_limits',
            field=models.IntegerField(null=True),
        ),
    ]
