# Generated by Django 2.1.1 on 2018-09-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180930_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='request_limits',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
