# Generated by Django 2.1.1 on 2018-09-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180930_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='request_limits',
            new_name='request_limits_developer',
        ),
        migrations.AddField(
            model_name='user',
            name='request_limits_organization',
            field=models.IntegerField(default=-1),
        ),
    ]
